site_name: LoveSexEager
site_url: https://lovesexeager.github.io 
site_author: lovesexeager
site_description: "A wiki for love and sexuality eagers"
copyright: "LoveSexEager is licensed under the <a href='https://github.com/lovesexeager/lovesexeager.github.io/blob/working/LICENSE'>MIT license</a>"
theme: cinder
markdown_extensions:
    - toc:
        permalink: "#"
