site_name: LoveSexWiki
site_url: https://lovesexwiki.github.io 
site_author: lovesexwiki
site_description: "A wiki for love and sexuality eagers"
copyright: "LoveSexEager is licensed under the <a href='https://mit-license.org'>MIT license</a>"
strict: true
theme: cinder
markdown_extensions:
    - smarty
    - sane_lists
    - toc:
        permalink: "#"
nav:
    - Home: 'index.md'
    - 'Come As You Are - Emily Nagoski': 
        - Overview: come_as_you_are_emily_nagoski/overview.md
        - Introduction: come_as_you_are_emily_nagoski/introduction_yes_you_are_normal.md
        - 'Chapter 9: Love what is true': come_as_you_are_emily_nagoski/chapter_9_love_what_is_true.md
        - 'Stories': come_as_you_are_emily_nagoski/stories.md 
        - Extra: 
            - 'Pain causes': come_as_you_are_emily_nagoski/extra/pain_causes.md 
              
